import { AuthCommonLang, ChatCommonLang, Dictionary, PresetClothesCommonLang } from './lang';

const authCommonDict: AuthCommonLang = {
	idText: 'ID',
	passwordText: 'パスワード',
	nicknameText: 'ニックネーム',
	passwordRegexPlaceholder: '英文字、数字、記号をすべて含む8〜15文字',
	countryCodeText: '国籍',
	countryCodeKR: '韓国',
	countryCodeJP: '日本',
	emailText: 'メール',
};

const chatCommonDict: ChatCommonLang = {
	receivedMessages: '受信メッセージ',
	sentMessage: '送信メッセージ',
	loadingMessage: '読み込み中...',
};

const presetClothesCommonDict: PresetClothesCommonLang = {
	category1: 'トップス',
	category2: 'ボトムス',
	category3: 'アウター',
	category4: 'シューズ',
	category5: 'アクセサリー',
};

/**
 * @file ja.ts
 * @description 일본어 다국어 사전을 정의하는 데이터 파일
 */
export const ja: Dictionary = {
	authCommonDict,
	chatCommonDict,
	presetClothesCommonDict,
	loginComponent: {
		...authCommonDict,
		successLoginToast: 'ログインが完了しました。',
		diffIdPasswordToast: 'IDまたはパスワードが一致しません。',
		loginErrorToast: 'ログイン中にエラーが発生しました。',
		loginText: 'ログイン',
		explainLoginText: 'サービスを利用するにはログインが必要です。',
		idPlaceholder: 'IDを入力してください',
		passwordPlaceholder: 'パスワードを入力してください',
		haveNotAccount: 'アカウントをお持ちでないですか？',
		registerText: '新規登録',
	},
	myPageComponent: {
		...authCommonDict,
		fixUserInfoText: '会員情報修正',
		explainFixUserInfoText: '会員情報を修正します。ID、ニックネーム、国籍、メールは修正できません。',
		currentPasswordText: '現在のパスワード',
		newPasswordText: '新しいパスワード',
		newPasswordConfirmText: '新しいパスワード確認',
		newPasswordConfirmPlaceholder: 'パスワード再入力',
		confirmFix: '修正',
		deleteAccount: '退会',
		cancel: 'キャンセル',
		passwordMatchSuccess: 'パスワードが一致しました。',
	},
	registerComponent: {
		...authCommonDict,
		registerText: '会員登録',
		explainRegisterText1: 'アカウント作成のため情報を入力してください。',
		explainRegisterText2: 'ID, ニックネーム, 国籍, メールは変更不可能です。',
		idPlaceholder: '英小文字, 数字 4~10文字',
		duplicateButton: '重複確認',
		passwordConfirmText: 'パスワード確認',
		passwordConfirmPlaceholder: 'パスワード再入力',
		nicknamePlaceholder: '英字, 数字, かな, 漢字 2~10文字',
		emailPlaceholder: 'メール入力',
		termText: 'サービス利用規約を表示',
		termAgree: '同意します',
		registerButton: '登録する',
		isHaveAccount: 'すでにアカウントをお持ちですか？',
		goLogin: 'ログイン画面へ',
		matchPassword: 'パスワードが一致しました。',
		isNotMatchPassword: 'パスワードが一致しません。',
	},
	chatSidebarComponent: {
		...chatCommonDict,
		messageText: 'メッセージ',
	},
	chatSidebarTabsComponent: {
		...chatCommonDict,
		writeMessage: 'メッセージ作成',
	},
	mailDetailHeaderComponent: {
		...chatCommonDict,
	},
	mailDetailViewComponent: {
		...chatCommonDict,
		messageNotFound: 'メッセージが見つかりません。',
	},
	mailItemComponent: {
		sender: '送信者:',
		receiver: '受信者',
		read: '既読',
		notRead: '未読',
	},
	receivedMailListComponent: {
		...chatCommonDict,
		notFoundReceivedMail: '受信メールはありません。',
	},
	sentMailListComponent: {
		...chatCommonDict,
		notFoundSendMail: '送信メールはありません。',
	},
	writeMailFormComponent: {
		...chatCommonDict,
		notFoundNickname: '存在しないニックネームです。',
		failSendMail: 'メッセージの送信に失敗しました。',
		receiverNickname: '受信者 (ニックネーム)',
		receiverNicknamePlaceholder: '受信者のニックネームを入力してください',
		content: '内容',
		contentPlaceholder: '内容を入力してください',
		sending: '送信中',
		send: '送信',
	},
	homeClientComponent: {
		maxLoadPost: 'これ以上読み込む投稿はありません。',
		notFoundPost: '投稿がありません。',
	},
	headerComponent: {
		logoutToast: 'ログアウトしました。',
		closet: 'マイクローゼット',
		openChat: 'チャットを開く',
		myPage: 'マイページ',
	},
	headerAuthComponent: {
		login: 'ログイン',
		register: '会員登録',
		honorifics: '様',
		logout: 'ログアウト',
	},
	langToggleComponent: {
		changeLanguage: '언어변경',
	},
	notificationHeaderComponent: {
		notificationText: '通知',
		readAll: 'すべて既読',
		readNotificationDelete: '既読の通知を削除',
	},
	notificationItemComponent: {
		who: 'さんが ',
		writtenComment: 'コメント',
		commentLast: 'を投稿しました。',
		board: 'さんがあなたの投稿に',
		likedBoard: 'いいねしました。',
		likeBoardLast: '',
		receivedMessage: 'メッセージ',
		send: 'を送信しました。',
		newLabel: '新着',
	},
	notificationListComponent: {
		notFoundNotification: '通知がありません。',
	},
	boardEtcComponent: {
		report: '通報',
		fix: '修正',
		delete: '削除',
		cancel: 'キャンセル',
	},
	boardSearchComponent: {
		searchPlaceholder: '検索したい投稿のタイトルや内容を入力してください。',
	},
	commentInputComponent: {
		writingReply: 'さんに返信中...',
		writeCommentPlaceholder: 'コメントを入力してください',
		writeComment: 'コメント投稿',
	},
	commentItemComponent: {
		changeComment: '変更',
		cancel: 'キャンセル',
		reply: '返信',
		edit: '修正',
		delete: '削除',
		report: '通報',
	},
	commentListComponent: {
		firstComment: '最初のコメントを投稿してください。',
	},
	globalCommentModalComponent: {
		loadingErrorToast: '投稿の読み込みに失敗しました。',
	},
	orderByWriteComponent: {
		recent: '新着順',
		like: 'いいね順',
		write: '投稿する',
	},
	translateAbleTextComponent: {
		translateSuccess: '翻訳が完了しました。',
		translateFail: '翻訳に失敗しました。',
	},
	writeContentFormAreaComponent: {
		titlePlaceholder: 'タイトルは40文字まで入力できます',
		contentPlaceholder: '内容を入力してください',
	},
	writeContentHeaderComponent: {
		cancel: 'キャンセル',
		submitting: '送信中',
		submit: '送信',
	},
	writeContentImageAreaComponent: {
		makingPresetImage: 'プリセット画像作成中',
		changeImage: '画像変更',
		selectImage: '画像選択',
		selectImageExplain: '画像をアップロードするかプリセットを選択してください',
	},
	presetCanvasPreviewComponent: {
		...presetClothesCommonDict,
		selectedPresetPreview: '選択したプリセットのプレビュー',
		selectedPresetPreviewExplain: '保存したコーデを選択すると、ここにプレビューが表示されます',
		none: 'なし',
	},
	presetEditorComponent: {
		...presetClothesCommonDict,
		loadError: 'プリセット情報を読み込めませんでした。',
		closetLoadError: '洋服データを読み込めませんでした。',
		categoryOnlyAllowed1: ' スロットには ',
		categoryOnlyAllowed2: 'のみ追加できます。',
		deleteConfirm: '保存したコーデを削除しますか？',
		deleteFail: 'コーデ削除失敗',
		requiredTopBottom: 'トップスとボトムスは必須です。',
		defaultTitle: 'マイコーデ',
		editSuccess: 'コーデの修正に成功しました',
		saveSuccess: 'コーデの保存に成功しました',
		editFail: 'コーデの修正中にエラーが発生しました',
		saveFail: 'コーデの保存中にエラーが発生しました',
		noName: '名前なし',
		dragToAddPrefix: 'このカテゴリーの服を',
		dragToAddSuffix: 'ドラッグまたはクリックして追加',
		category: 'カテゴリー',
		viewAll: 'すべて表示',
		season: '季節',
		savedPresets: '保存されたプリセット',
		noSavedPresets: 'まだ保存されたコーデがありません。',
		edit: '修正',
		delete: '削除',
		makePresetMode: 'コーデを作成',
		editPresetMode: 'コーデ修正',
		makePresetDesc: '自分だけのスタイルを組み合わせて新しいコーデを完成させてみてください。',
		titlePlaceholder: 'コーデ名を入力',
		saveEdit: '修正保存',
		save: '保存',
		goBack: '戻る',
		myClothesList: 'マイ服リスト',
		selectCategory: 'カテゴリー',
		selected: '選択済',
		select: '選択する',
		viewPreset: 'コーデを見る',
	},
	presetSelectorListComponent: {
		noSavedPresets: '保存したプリセットがありません。',
		savedPresets: '保存したプリセット',
	},
	presetPreviewCardComponent: {
		noImage: '画像なし',
		delete: '削除',
	},
	categoryComponent: {
		board: '投稿',
		news: 'ファッションニュース',
		clothes: 'マイクローゼット',
		preset: 'プリセット',
	},
	weatherComponent: {
		noInfo: '情報なし',
		noInfoExplain: '天気情報を\n取得できません。',
		humidity: '湿度',
		wind: '風速',
	},
	termComponent: {
		termsTitle: 'OTTAKU サービス利用規約および個人情報処理方針',
		termsSec1Title: '投稿および画像の著作権と保護',
		termsSec1Item1Title: '権利と責任:',
		termsSec1Item1Desc:
			'会員がサイト内の掲示板に登録したコーデ写真、スタイリングショットなどすべてのテキストと画像の著作権は作成者本人にあり、それに伴う責任も作成者にあります。',
		termsSec1Item2Title: '無断盗用および不法使用禁止:',
		termsSec1Item2Desc:
			'他の会員が共有した画像やコンテンツを原作者の明示的な事前同意なしにキャプチャ、保存、複製、配布したり商業目的/非商業的目的で使用する行為を厳格に禁止します。',
		termsSec1Item3Title: '保護措置:',
		termsSec1Item3Desc:
			'他人の画像を無断で盗用したり権利を侵害する投稿が発見（または通報）された場合、管理者は円滑なコミュニティ環境作りのため、事前通知なしに該当投稿を削除処理することができます。これにより発生するすべての法的責任は作成者本人にあります。',
		termsSec2Title: '会員間のコミュニケーション利用',
		termsSec2Item1Title: '利用目的および権利保護:',
		termsSec2Item1Desc:
			'DM機能は会員間のコーデ情報共有など純粋な疎通のために提供され、個人間の対話内容は原則として保護されます。',
		termsSec2Item2Title: '禁止行為:',
		termsSec2Item2Desc:
			'DMを利用してスパムメッセージ, 無断商業的広告, 悪口, 誹謗, 性的羞恥心を誘発する内容などを送信する行為を厳格に禁止します。',
		termsSec2Item3Title: '通報および制裁:',
		termsSec2Item3Desc:
			'禁止行為による被害通報が受け付けられた場合, 管理者は快適で安全なコミュニティ環境作りのため関連メッセージ内訳を確認し, 該当ユーザーのサービス利用を制限することができます。',
		termsSec3Title: '個人情報の収集および利用',
		termsSec3Intro: '会員に安全で便利なサービスを提供するため、以下のような最小限の情報を収集して管理しています。',
		termsSec3Item1Title: '会員管理および疎通のための情報',
		termsSec3Item1Bullet1: '収集項目: メールアドレス',
		termsSec3Item1Bullet2:
			'収集目的: サービス利用のための本人識別, 加入および退会処理, ID探し, パスワード紛失時の再設定。',
		termsSec3Item2Title: '安全なサービス環境作りのための情報',
		termsSec3Item2Bullet1: '収集項目: ネットワーク接続位置データ, 機器環境情報, サービス利用記録',
		termsSec3Item2Bullet2:
			'収集目的: ユーザーの大まかな接続地域を把握して現在の天気に合ったカスタムコンテンツを円滑に提供するために活用されます。併せて快適なサイト利用環境の維持、システムエラー分析、そして異常なアプローチ（アビュージング）から善良な利用者を保護するためのセキュリティおよび統計資料としても使用されます。',
		termsSec4Title: '情報の保管および破棄',
		termsSec4Desc:
			'収集されたメールおよびサービス利用記録は、会員が退会を要請したり個人情報同意を撤回する場合、関連法令に特別な規定がない限り、遅滞なく安全な方法で永久破棄されます。',
	},
	useBoard: {
		boardLoadError: '投稿の読み込みに失敗しました。',
		presetLoadError: 'プリセットの読み込みに失敗しました。',
		presetCaptureFail: 'プリセット画像生成に失敗しました。',
		titleRequired: 'タイトルを入力してください。',
		contentRequired: '内容を作成してください。',
		imageRequired: '画像を選択するかプリセットをロードしてください。',
		editSuccess: '投稿を修正しました。',
		writeSuccess: '投稿を完了しました。',
		uploadFail: 'アップロード失敗',
		imageOnlyError: '画像ファイルのみアップロード可能です。',
	},
	useChat: {
		receiveMessageLoadError: '受信メッセージの読み込みに失敗しました。',
		sendMessageLoadError: '送信メッセージの読み込みに失敗しました。',
		detailMessageLoadError: 'メッセージ詳細情報の読み込みに失敗しました。',
		sendMessageSuccess: 'メッセージを送信しました。',
		sendMessageFail: 'メッセージ送信に失敗しました。',
	},
	useComment: {
		commentLoadError: 'コメントの読み込みに失敗しました。',
		commentWriteSuccess: 'コメントを投稿しました。',
		commentWriteFail: 'コメント投稿に失敗しました。',
		deleteConfirm: 'コメントを削除しますか？',
		deleteSuccess: 'コメントを削除しました。',
		notAuthorError: '本人が作成したコメントのみ削除できます。',
		deleteFail: 'コメント削除に失敗しました。',
		editSuccess: 'コメントを修正しました。',
		editFail: 'コメント修正に失敗しました。',
		commentTitle: 'コメント',
		reportPrompt: '通報事由を入力してください',
		reportSuccess: 'コメントを通報しました',
		reportFail: 'コメント通報に失敗しました',
	},
	usePostActions: {
		likeError: 'いいね処理に失敗しました。',
		bookmarkError: 'ブックマーク処理に失敗しました。',
		deleteConfirm: '投稿を削除しますか？',
		deleteSuccess: '投稿を削除しました。',
		notAuthorError: '本人が作成した投稿のみ削除できます。',
		deleteFail: '投稿削除に失敗しました。',
		reportPrompt: '通報事由を入力してください。',
		reportSuccess: '投稿を通報しました。',
		alreadyReportedError: 'すでに通報済みの投稿です。',
		reportFail: '投稿通報に失敗しました。',
	},
	useRegister: {
		idRequired: 'IDを入力してください。',
		idRegexError: 'IDは 4~10文字の英小文字、数字のみ使用可能です。',
		idDuplicateError: '既に使用されているIDです。',
		idAvailable: '使用可能なIDです。',
		idCheckError: 'ID重複確認中にエラーが発生しました。',
		nicknameRequired: 'ニックネームを入力してください',
		nicknameRegexError: 'ニックネームは 2~10文字の英字、数字、かな、漢字のみ使用可能です。',
		nicknameDuplicateError: '既に使用されているニックネームです。',
		nicknameAvailable: '使用可能なニックネームです。',
		nicknameCheckError: 'ニックネーム重複確認中にエラーが発生しました。',
		emailRequired: 'メールアドレスを入力してください',
		emailRegexError: '無効なメール形式です。',
		emailDuplicateError: '既に使用されているメールアドレスです。',
		emailAvailable: '使用可能なメールアドレスです。',
		emailCheckError: 'メール重複確認中にエラーが発生しました。',
		idCheckRequired: 'IDの重複確認を行ってください。',
		emailCheckRequired: 'メールの重複確認を行ってください。',
		nicknameCheckRequired: 'ニックネームの重複確認を行ってください。',
		passwordRegexError: 'パスワードは 8~15文字の英字、数字、特殊文字をすべて含む必要があります。',
		passwordMismatchError: 'パスワードが一致しません。',
		registerSuccess: '会員登録が完了しました。',
		genericError: '問題が発生しました。もう一度お試しください。',
	},
	useRequireAuth: {
		requireLogin: 'ログインが必要です。',
	},
	userInfoSearchComponent: {
		findUsername: 'ID探し',
		changePassword: 'パスワード変更',
		inputEmailExplain: '加入したメールを入力してください。',
		inputNewPasswordExplain: 'メール認証後、新しいパスワードを入力してください。',
		email: 'メール',
		emailPlaceholder: 'メール入力',
		check: '確認',
		newPassword: '新しいパスワード',
		newPasswordConfirm: '新しいパスワード確認',
		passwordMatch: 'パスワードが一致します。',
		passwordMismatch: 'パスワードが一致しません。',
		foundIdPrefix: '登録されたIDは ',
		foundIdSuffix: ' です。',
		changePasswordButton: 'パスワード変更',
		knowAccount: 'アカウントをお持ちですか？',
		goLogin: 'ログイン画面へ',
		emailRequired: 'メールを入力してください。',
		invalidEmail: '無効なメール形式です。',
		emailInUse: '既に使用されているメールアドレスです。',
		emailNotFound: '登録されていないメールアドレスです。',
		checkError: '重複確認中にエラーが発生しました。',
		emailCheckRequired: 'メール重複確認を行ってください。',
		passwordRegexError: 'パスワードは 8~15文字の英字、数字、特殊文字をすべて含む必要があります。',
	},
	closetPageComponent: {
		spring: '春',
		summer: '夏',
		autumn: '秋',
		winter: '冬',
		veryCold: 'とても寒い',
		chilly: '肌寒い',
		cool: '涼しい',
		warm: '暖かい',
		veryHot: 'とても暑い',
		veryColdDesc: '厚手のアウター中心の推奨',
		chillyDesc: '秋冬アイテムの推奨',
		coolDesc: '春秋用上下推奨',
		warmDesc: '夏/春アイテム推奨',
		veryHotDesc: '真夏用軽いアイテム推奨',
		dataLoadError: 'データを読み込めませんでした。',
		item: 'アイテム',
		deleteConfirm: '本当に削除しますか？',
		deleteError: '削除中にエラーが発生しました。',
		presetDeleteConfirm: '保存されたプリセットを削除しますか？',
		presetDeleteFail: 'プリセット削除失敗',
		category: 'カテゴリー',
		viewAll: 'すべて表示',
		season: '季節',
		savedPresets: '保存されたプリセット',
		noPresets: 'まだ保存されたプリセットがありません。',
		edit: '修正',
		delete: '削除',
		myCloset: 'マイクローゼット',
		closetDesc: '所有している服を管理し、現在の天気に合わせた最適なコーディネートの提案を受けてみてください。',
		searchPlaceholder: 'アイテム検索...',
		addPreset: 'プリセット登録',
		addCloth: 'アイテム登録',
		todayRecommendation: '今日のコーディネート提案',
		weatherLoadError: '天気情報を読み込めませんでした。',
		recommendedCloth: 'おすすめアイテム',
		noRecommendation: '提案可能なアイテムが見つかりません。もっと多くのアイテムを登録してください！',
		noMatchingCloth: '条件に合うアイテムがありません。',
	},
	closetItemCardComponent: {
		item: 'アイテム',
		noImage: '画像なし',
		noName: '名前なし',
		edit: '修正',
		delete: '削除',
		selected: '選択済み',
		select: '選択',
	},
	closetFormComponent: {
		addTitle: '服の登録',
		editTitle: 'アイテム修正',
		addDesc: '服の登録フォームを記入してください。',
		editDesc: 'アイテムに保存された情報を修正できます。',
		itemName: '服の名前',
		itemNamePlaceholder: 'アイテムの名前を入力してください',
		imageUpload: '画像アップロード',
		imageEdit: '画像修正',
		imageGuide: '画像をここにドラッグするか、ファイル選択ボタンを押してください。',
		imageSizeGuide: '画像ファイルは最大10MBまでアップロード可能です。',
		selectFile: 'ファイルを選択',
		preview: 'プレビュー',
		category: 'カテゴリー',
		categorySelect: 'カテゴリー選択',
		season: '季節',
		seasonSelect: '季節選択',
		cancel: 'キャンセル',
		submittingAdd: '登録中...',
		submittingEdit: '修正中...',
		submitAdd: 'アイテム登録',
		submitEdit: '情報修正',
		categoryLoadError: 'カテゴリーの読み込み中にエラーが発生しました。',
		imageOnlyError: '画像ファイルのみアップロード可能です。',
		imageSizeError: '10MB以下の画像ファイルのみアップロード可能です。',
		allFieldsRequired: 'すべての情報を入力して画像を登録してください',
		addSuccess: '登録されました。',
		addError: '登録中にエラーが発生しました。',
		editSuccess: '修正されました。',
		editError: '修正中にエラーが発生しました。',
		loadError: '服の情報を読み込めませんでした。',
		loading: '読み込み中...',
	},
	myPresetComponent: {
		title: '保存されたプリセットリスト',
		desc: '作成したプリセットを確認してください。',
		addNew: '新しいプリセットを作成',
		loading: 'プリセットを読み込んでいます...',
		edit: 'プリセット修正',
		delete: 'プリセット削除',
		loadError: 'プリセットリストを読み込めませんでした.',
		deleteConfirm: 'このプリセットを削除しますか?',
		deleteSuccess: '削除されました.',
		deleteError: '削除中にエラーが発生しました.',
	},
	shadcnDialog: {
		confirm: '確認',
		cancel: 'キャンセル',
	},
};
