import { AuthCommonLang, ChatCommonLang, Dictionary, PresetClothesCommonLang } from './lang';

const authCommonDict: AuthCommonLang = {
	idText: '아이디',
	passwordText: '비밀번호',
	nicknameText: '닉네임',
	passwordRegexPlaceholder: '영문, 숫자, 특수문자를 모두 포함한 8~15자',
	countryCodeText: '국적',
	countryCodeKR: '한국',
	countryCodeJP: '일본',
	emailText: '이메일',
};

const chatCommonDict: ChatCommonLang = {
	receivedMessages: '받은 메시지',
	sentMessage: '보낸 메시지',
	loadingMessage: '불러오는 중...',
};

const presetClothesCommonDict: PresetClothesCommonLang = {
	category1: '상의',
	category2: '하의',
	category3: '아우터',
	category4: '신발',
	category5: '액세서리',
};

/**
 * @file ko.ts
 * @description 한국어 다국어 사전을 정의하는 데이터 파일
 */
export const ko: Dictionary = {
	authCommonDict,
	chatCommonDict,
	presetClothesCommonDict,
	loginComponent: {
		...authCommonDict,
		successLoginToast: '로그인이 완료되었습니다.',
		diffIdPasswordToast: '아이디 또는 비밀번호가 일치하지 않습니다.',
		loginErrorToast: '로그인 중 오류가 발생했습니다.',
		loginText: '로그인',
		explainLoginText: '서비스 이용을 위해 로그인이 필요합니다.',
		idPlaceholder: '아이디를 입력해주세요',
		passwordPlaceholder: '비밀번호를 입력해주세요',
		haveNotAccount: '계정이 없으신가요?',
		registerText: '회원가입',
	},
	myPageComponent: {
		...authCommonDict,
		fixUserInfoText: '회원정보 수정',
		explainFixUserInfoText: '회원 정보를 수정합니다. 아이디, 닉네임, 국적, 이메일은 수정할 수 없습니다.',
		currentPasswordText: '현재 비밀번호',
		newPasswordText: '새 비밀번호',
		newPasswordConfirmText: '새 비밀번호 확인',
		newPasswordConfirmPlaceholder: '비밀번호 재입력',
		confirmFix: '수정',
		deleteAccount: '회원탈퇴',
		cancel: '취소',
		passwordMatchSuccess: '비밀번호가 일치합니다.',
	},
	registerComponent: {
		...authCommonDict,
		registerText: '회원가입',
		explainRegisterText1: '계정 생성을 위해 정보를 입력해주세요.',
		explainRegisterText2: '아이디, 닉네임, 국적, 이메일은 변경이 불가능합니다.',
		idPlaceholder: '영문 소문자, 숫자 4~10자',
		duplicateButton: '중복 확인',
		passwordConfirmText: '비밀번호 확인',
		passwordConfirmPlaceholder: '비밀번호 재입력',
		nicknamePlaceholder: '영문, 숫자, 가나, 한자 2~10글자',
		emailPlaceholder: '이메일 입력',
		termText: '서비스 이용 약관 보기',
		termAgree: '동의합니다',
		registerButton: '가입하기',
		isHaveAccount: '이미 계정이 있으신가요?',
		goLogin: '로그인 하기',
		matchPassword: '비밀번호가 일치합니다.',
		isNotMatchPassword: '비밀번호가 일치하지 않습니다.',
	},
	chatSidebarComponent: {
		...chatCommonDict,
		messageText: '메시지',
	},
	chatSidebarTabsComponent: {
		...chatCommonDict,
		writeMessage: '메시지 쓰기',
	},
	mailDetailHeaderComponent: {
		...chatCommonDict,
	},
	mailDetailViewComponent: {
		...chatCommonDict,
		messageNotFound: '메시지를 찾을 수 없습니다.',
	},
	mailItemComponent: {
		sender: '보낸 사람:',
		receiver: '받는 사람',
		read: '읽음',
		notRead: '읽지 않음',
	},
	receivedMailListComponent: {
		...chatCommonDict,
		notFoundReceivedMail: '받은 메일이 없습니다.',
	},
	sentMailListComponent: {
		...chatCommonDict,
		notFoundSendMail: '보낸 메일이 없습니다.',
	},
	writeMailFormComponent: {
		...chatCommonDict,
		notFoundNickname: '존재하지 않는 닉네임입니다.',
		failSendMail: '메시지 전송에 실패했습니다.',
		receiverNickname: '받는 사람 (닉네임)',
		receiverNicknamePlaceholder: '받는 사람의 닉네임을 입력하세요',
		content: '내용',
		contentPlaceholder: '내용을 입력하세요',
		sending: '전송중',
		send: '보내기',
	},
	homeClientComponent: {
		maxLoadPost: '불러올 게시글이 더 이상 없습니다.',
		notFoundPost: '게시글이 없습니다.',
	},
	headerComponent: {
		logoutToast: '로그아웃 되었습니다.',
		closet: '내 옷장',
		openChat: '채팅 열기',
		myPage: '마이페이지',
	},
	headerAuthComponent: {
		login: '로그인',
		register: '회원가입',
		honorifics: '님',
		logout: '로그아웃',
	},
	langToggleComponent: {
		changeLanguage: '言語変更',
	},
	notificationHeaderComponent: {
		notificationText: '알림',
		readAll: '모두 읽음',
		readNotificationDelete: '읽은 알림 모두 삭제',
	},
	notificationItemComponent: {
		who: '님이 ',
		writtenComment: '댓글',
		commentLast: '을 작성했습니다.',
		board: '님이 회원님의',
		likedBoard: ' 게시글을 좋아합니다.',
		likeBoardLast: '',
		receivedMessage: '메시지',
		send: '를 보냈습니다.',
		newLabel: '신규',
	},
	notificationListComponent: {
		notFoundNotification: '알림이 없습니다.',
	},
	boardEtcComponent: {
		report: '신고',
		fix: '수정',
		delete: '삭제',
		cancel: '취소',
	},
	boardSearchComponent: {
		searchPlaceholder: '제목 또는 내용을 입력해주세요.',
	},
	commentInputComponent: {
		writingReply: '님에게 답글 남기는 중...',
		writeCommentPlaceholder: '댓글을 입력해주세요',
		writeComment: '댓글 작성',
	},
	commentItemComponent: {
		changeComment: '변경',
		cancel: '취소',
		reply: '답글',
		edit: '수정',
		delete: '삭제',
		report: '신고',
	},
	commentListComponent: {
		firstComment: '첫 댓글을 작성해주세요.',
	},
	globalCommentModalComponent: {
		loadingErrorToast: '해당 게시글 로딩에 실패했습니다.',
	},
	orderByWriteComponent: {
		recent: '최신순',
		like: '좋아요순',
		write: '글쓰기',
	},
	translateAbleTextComponent: {
		translateSuccess: '번역이 완료되었습니다.',
		translateFail: '번역에 실패했습니다.',
	},
	writeContentFormAreaComponent: {
		titlePlaceholder: '제목은 40자까지 입력 가능합니다.',
		contentPlaceholder: '내용을 입력해주세요',
	},
	writeContentHeaderComponent: {
		cancel: '취소',
		submitting: '전송 중',
		submit: '전송',
	},
	writeContentImageAreaComponent: {
		makingPresetImage: '프리셋 이미지 만드는 중',
		changeImage: '이미지 변경',
		selectImage: '이미지 선택',
		selectImageExplain: '이미지를 업로드하거나 프리셋을 선택해주세요',
	},
	presetCanvasPreviewComponent: {
		...presetClothesCommonDict,
		selectedPresetPreview: '선택한 프리셋 미리보기',
		selectedPresetPreviewExplain: '저장한 프리셋 선택하면 여기에 미리보기가 표시됩니다.',
		none: '없음',
	},
	presetEditorComponent: {
		...presetClothesCommonDict,
		loadError: '프리셋 정보를 불러오지 못했습니다.',
		closetLoadError: '옷장 데이터를 불러오지 못했습니다.',
		categoryOnlyAllowed1: ' 슬롯에는 ',
		categoryOnlyAllowed2: '만 넣을 수 있습니다.',
		deleteConfirm: '저장한 프리셋을 삭제할까요?',
		deleteFail: '프리셋 삭제 실패',
		requiredTopBottom: '상의와 하의는 필수입니다.',
		defaultTitle: '내 프리셋',
		editSuccess: '프리셋 수정 성공',
		saveSuccess: '프리셋 저장 성공',
		editFail: '프리셋 수정 중 오류 발생',
		saveFail: '프리셋 저장 중 오류 발생',
		noName: '이름 없음',
		dragToAddPrefix: '이 카테고리 옷을',
		dragToAddSuffix: '드래그하거나 클릭해서 추가',
		category: '카테고리',
		viewAll: '전체 보기',
		season: '계절',
		savedPresets: '저장된 프리셋',
		noSavedPresets: '아직 저장된 프리셋이 없습니다.',
		edit: '수정',
		delete: '삭제',
		makePresetMode: '프리셋 만들기',
		editPresetMode: '프리셋 수정',
		makePresetDesc: '나만의 스타일을 조합하고 새로운 프리셋 완성해보세요.',
		titlePlaceholder: '프리셋 이름 입력',
		saveEdit: '수정 저장',
		save: '저장',
		goBack: '돌아가기',
		myClothesList: '내 옷 목록',
		selectCategory: '카테고리',
		selected: '선택됨',
		select: '선택하기',
		viewPreset: '프리셋 보기',
	},
	presetSelectorListComponent: {
		noSavedPresets: '저장한 프리셋이 없습니다.',
		savedPresets: '저장한 프리셋',
	},
	presetPreviewCardComponent: {
		noImage: '이미지 없음',
		delete: '삭제',
	},
	categoryComponent: {
		board: '게시글',
		news: '패션 뉴스',
		clothes: '내 옷장',
		preset: '프리셋',
	},
	weatherComponent: {
		noInfo: '정보 없음',
		noInfoExplain: '날씨 정보를\n가져올 수 없습니다.',
		humidity: '습도',
		wind: '풍속',
	},
	termComponent: {
		termsTitle: 'OTTAKU 서비스 이용 및 개인정보 처리 방침',
		termsSec1Title: '게시물 및 이미지의 저작권과 보호',
		termsSec1Item1Title: '권리와 책임:',
		termsSec1Item1Desc:
			'회원이 사이트 내 게시판에 등록한 코디 사진, 스타일링 샷 등 모든 텍스트와 이미지의 저작권은 작성자 본인에게 있으며, 그에 따른 책임 역시 작성자에게 있습니다.',
		termsSec1Item2Title: '무단 도용 및 불법 사용 금지:',
		termsSec1Item2Desc:
			'다른 회원이 공유한 이미지나 콘텐츠를 원작자의 명시적인 사전 동의 없이 캡처, 저장, 복제, 배포하거나 상업적/비상업적 용도로 사용하는 행위를 엄격히 금지합니다.',
		termsSec1Item3Title: '보호 조치:',
		termsSec1Item3Desc:
			'타인의 이미지를 무단으로 도용하거나 권리를 침해하는 게시물이 발견(또는 신고)될 경우, 관리자는 원활한 커뮤니티 환경 조성을 위해 사전 통보 없이 해당 게시물을 삭제 처리할 수 있습니다. 이로 인해 일어나는 모든 법적 책임은 작성자 본인에게 있습니다.',
		termsSec2Title: '회원 간 커뮤니케이션 이용',
		termsSec2Item1Title: '이용 목적 및 권리 보호:',
		termsSec2Item1Desc:
			'DM 기능은 회원 간의 코디 정보 공유 등 순수한 소통을 위해 제공되며, 개인 간의 대화 내용은 원칙적으로 보호됩니다.',
		termsSec2Item2Title: '금지 행위:',
		termsSec2Item2Desc:
			'DM을 이용하여 스팸 메시지, 무단 상업적 광고, 욕설, 비방, 성적 수치심을 유발하는 내용 등을 전송하는 행위를 엄격히 금지합니다.',
		termsSec2Item3Title: '신고 및 제재:',
		termsSec2Item3Desc:
			'금지 행위로 인한 피해 신고가 접수될 경우, 관리자는 쾌적하고 안전한 커뮤니티 환경 조성을 위해 관련 메시지 내역을 확인하고 가해 회원의 서비스 이용을 제한할 수 있습니다.',
		termsSec3Title: '개인정보 수집 및 이용',
		termsSec3Intro:
			'회원들에게 안전하고 편리한 서비스를 제공하기 위해 아래와 같은 최소한의 정보를 수집하여 관리하고 있습니다.',
		termsSec3Item1Title: '회원 관리 및 소통을 위한 정보',
		termsSec3Item1Bullet1: '수집 항목: 이메일 주소',
		termsSec3Item1Bullet2:
			'수집 목적: 서비스 이용을 위한 본인 식별, 가입 및 탈퇴 처리, 아이디 찾기, 비밀번호 분실 시 재설정.',
		termsSec3Item2Title: '안전한 서비스 환경 조성을 위한 정보',
		termsSec3Item2Bullet1: '수집 항목: 네트워크 접속 위치 데이터, 기기 환경 정보, 서비스 이용 기록',
		termsSec3Item2Bullet2:
			'수집 목적: 사용자의 대략적인 접속 지역을 파악하여 현재 날씨에 맞는 맞춤형 콘텐츠를 원활하게 제공하기 위해 활용됩니다. 아울러 쾌적한 사이트 이용 환경 유지, 시스템 오류 분석, 그리고 비정상적인 접근(어뷰징)으로부터 선량한 이용자를 보호하기 위한 보안 및 통계 자료로도 사용됩니다.',
		termsSec4Title: '정보의 보관 및 파기',
		termsSec4Desc:
			'수집된 이메일 및 서비스 이용 기록은 회원이 탈퇴를 요청하거나 개인정보 동의를 철회할 경우, 관련 법령에 특별한 규정이 없는 한 지체 없이 안전한 방법으로 영구 파기됩니다.',
	},
	useBoard: {
		boardLoadError: '게시글을 불러오는데 실패했습니다.',
		presetLoadError: '프리셋을 불러오는데 실패했습니다.',
		presetCaptureFail: '프리셋 이미지 생성에 실패했습니다.',
		titleRequired: '제목을 입력해주세요.',
		contentRequired: '내용을 작성해주세요.',
		imageRequired: '이미지를 선택하거나 프리셋을 로드해주세요.',
		editSuccess: '게시글이 수정되었습니다.',
		writeSuccess: '게시글이 작성되었습니다.',
		uploadFail: '업로드 실패.',
		imageOnlyError: '이미지 파일만 업로드할 수 있습니다.',
	},
	useChat: {
		receiveMessageLoadError: '받은 메시지를 불러오는데 실패했습니다.',
		sendMessageLoadError: '보낸 메시지를 불러오는데 실패했습니다.',
		detailMessageLoadError: '메시지 상세 정보를 불러오는데 실패했습니다.',
		sendMessageSuccess: '메시지를 전송했습니다.',
		sendMessageFail: '메시지 전송에 실패했습니다.',
	},
	useComment: {
		commentLoadError: '댓글을 불러오는데 실패했습니다.',
		commentWriteSuccess: '댓글을 작성했습니다.',
		commentWriteFail: '댓글 작성에 실패했습니다.',
		deleteConfirm: '댓글을 삭제하시겠습니까?',
		deleteSuccess: '댓글을 삭제했습니다.',
		notAuthorError: '본인이 작성한 댓글만 삭제할 수 있습니다.',
		deleteFail: '댓글 삭제에 실패했습니다.',
		editSuccess: '댓글을 수정했습니다.',
		editFail: '댓글 수정에 실패했습니다.',
		commentTitle: '댓글',
		reportPrompt: '신고 사유를 입력해주세요',
		reportSuccess: '댓글이 신고되었습니다.',
		reportFail: '댓글 신고에 실패했습니다.',
	},
	usePostActions: {
		likeError: '좋아요 처리에 실패했습니다.',
		bookmarkError: '북마크 처리에 실패했습니다.',
		deleteConfirm: '게시글을 삭제하시겠습니까?',
		deleteSuccess: '게시글이 삭제되었습니다.',
		notAuthorError: '본인이 작성한 게시글만 삭제할 수 있습니다.',
		deleteFail: '게시글 삭제에 실패했습니다.',
		reportPrompt: '신고 사유를 입력해주세요.',
		reportSuccess: '게시글이 신고되었습니다.',
		alreadyReportedError: '이미 신고된 게시글입니다.',
		reportFail: '게시글 신고에 실패했습니다.',
	},
	useRegister: {
		idRequired: '아이디를 입력해주세요.',
		idRegexError: '아이디는 4~10자의 영문 소문자와 숫자만 사용 가능합니다.',
		idDuplicateError: '이미 사용 중인 아이디입니다.',
		idAvailable: '사용 가능한 아이디입니다.',
		idCheckError: '아이디 중복 확인 도중에 에러가 발생했습니다.',
		nicknameRequired: '닉네임을 입력해주세요',
		nicknameRegexError: '닉네임은 2~10글자의 영문, 숫자, 가나, 한자만 사용 가능합니다.',
		nicknameDuplicateError: '이미 사용 중인 닉네임입니다.',
		nicknameAvailable: '사용 가능한 닉네임입니다.',
		nicknameCheckError: '닉네임 중복 확인 도중에 에러가 발생했습니다.',
		emailRequired: '이메일을 입력해주세요',
		emailRegexError: '유효하지 않은 이메일 형식입니다.',
		emailDuplicateError: '이미 사용 중인 이메일입니다.',
		emailAvailable: '사용 가능한 이메일입니다.',
		emailCheckError: '이메일 중복 확인 도중에 에러가 발생했습니다.',
		idCheckRequired: '아이디 중복 확인을 해주세요.',
		emailCheckRequired: '이메일 중복 확인을 해주세요.',
		nicknameCheckRequired: '닉네임 중복 확인을 해주세요.',
		passwordRegexError: '비밀번호는 8~15자의 영문, 숫자, 특수문자를 모두 포함해야 합니다.',
		passwordMismatchError: '비밀번호이 일치하지 않습니다.',
		registerSuccess: '회원가입이 완료되었습니다.',
		genericError: '문제가 발생했습니다. 다시 시도해주세요.',
	},
	useRequireAuth: {
		requireLogin: '로그인이 필요한 기능입니다.',
	},
	userInfoSearchComponent: {
		findUsername: '아이디 찾기',
		changePassword: '비밀번호 변경',
		inputEmailExplain: '가입하신 이메일을 입력해주세요.',
		inputNewPasswordExplain: '이메일 인증 후 새 비밀번호를 입력해주세요.',
		email: '이메일',
		emailPlaceholder: '이메일 입력',
		check: '확인',
		newPassword: '새 비밀번호',
		newPasswordConfirm: '새 비밀번호 확인',
		passwordMatch: '비밀번호가 일치합니다.',
		passwordMismatch: '비밀번호가 일치하지 않습니다.',
		foundIdPrefix: '등록된 아이디는 ',
		foundIdSuffix: ' 입니다.',
		changePasswordButton: '비밀번호 변경',
		knowAccount: '계정을 알고 있으신가요?',
		goLogin: '로그인 하기',
		emailRequired: '이메일을 입력해주세요.',
		invalidEmail: '유효하지 않은 이메일 형식입니다.',
		emailInUse: '이미 사용 중인 이메일입니다.',
		emailNotFound: '가입되지 않은 이메일입니다.',
		checkError: '중복 확인 중 오류가 발생했습니다.',
		emailCheckRequired: '이메일 중복 확인을 해주세요.',
		passwordRegexError: '비밀번호는 8~15자의 영문, 숫자, 특수문자를 모두 포함해야 합니다.',
	},
	closetPageComponent: {
		spring: '봄',
		summer: '여름',
		autumn: '가을',
		winter: '겨울',
		veryCold: '매우 추움',
		chilly: '쌀쌀함',
		cool: '선선함',
		warm: '따뜻함',
		veryHot: '매우 더움',
		veryColdDesc: '두꺼운 아우터 위주 추천',
		chillyDesc: '가을/겨울 아이템 추천',
		coolDesc: '봄/가을용 상하의 추천',
		warmDesc: '여름/봄 아이템 추천',
		veryHotDesc: '한여름용 가벼운 아이템 추천',
		dataLoadError: '데이터를 불러오지 못했습니다.',
		item: '아이템',
		deleteConfirm: '정말 삭제할까요?',
		deleteError: '삭제 중 오류가 발생했습니다.',
		presetDeleteConfirm: '저장된 프리셋을 삭제할까요?',
		presetDeleteFail: '프리셋 삭제 실패',
		category: '카테고리',
		viewAll: '전체 보기',
		season: '계절',
		savedPresets: '저장된 프리셋',
		noPresets: '아직 저장된 프리셋이 없습니다.',
		edit: '수정',
		delete: '삭제',
		myCloset: '나만의 옷장',
		closetDesc: '소유하고 있는 옷을 관리하고 현재 날씨에 어울리는 최적의 옷을 제안받아 보세요.',
		searchPlaceholder: '아이템 검색...',
		addPreset: '프리셋 등록',
		addCloth: '옷 등록',
		todayRecommendation: '오늘의 옷 추천',
		weatherLoadError: '날씨 정보를 불러올 수 없습니다.',
		recommendedCloth: '추천 옷',
		noRecommendation: '추천 가능한 옷을 찾을 수 없습니다. 더 많은 옷을 등록해주세요!',
		noMatchingCloth: '조합 조건에 맞는 옷이 없습니다.',
	},
	closetItemCardComponent: {
		item: '아이템',
		noImage: '이미지 없음',
		noName: '이름 없음',
		edit: '수정',
		delete: '삭제',
		selected: '선택됨',
		select: '선택',
	},
	closetFormComponent: {
		addTitle: '옷 등록',
		editTitle: '아이템 수정',
		addDesc: '옷 등록 양식을 작성해주세요.',
		editDesc: '옷에 저장된 정보를 수정할 수 있습니다.',
		itemName: '옷 이름',
		itemNamePlaceholder: '아이템 이름을 입력하세요',
		imageUpload: '이미지 업로드',
		imageEdit: '이미지 수정',
		imageGuide: '이미지를 여기에 드래그하거나 파일 선택하기 버튼을 눌러주세요.',
		imageSizeGuide: '이미지 파일은 최대 10MB까지 업로드 가능합니다.',
		selectFile: '파일 선택하기',
		preview: '미리보기',
		category: '카테고리',
		categorySelect: '카테고리 선택',
		season: '계절',
		seasonSelect: '계절 선택',
		cancel: '취소',
		submittingAdd: '등록 중...',
		submittingEdit: '수정 중...',
		submitAdd: '아이템 등록',
		submitEdit: '정보 수정',
		categoryLoadError: '카테고리 불러오는 중에 에러 발생.',
		imageOnlyError: '이미지 파일만 업로드할 수 있습니다.',
		imageSizeError: '10MB 이하 이미지 파일만 업로드할 수 있습니다.',
		allFieldsRequired: '모든 정보를 입력하고 이미지를 등록해주세요.',
		addSuccess: '등록되었습니다.',
		addError: '등록 중 오류가 발생했습니다.',
		editSuccess: '수정되었습니다.',
		editError: '수정 중 오류가 발생했습니다.',
		loadError: '옷 정보를 불러오지 못했습니다.',
		loading: '불러오는 중...',
	},
	myPresetComponent: {
		title: '저장된 프리셋 목록',
		desc: '내가 만든 프리셋을 확인하세요.',
		addNew: '새 프리셋 만들기',
		loading: '프리셋을 불러오는 중입니다...',
		edit: '프리셋 수정',
		delete: '프리셋 삭제',
		loadError: '프리셋 목록을 불러오지 못했습니다.',
		deleteConfirm: '이 프리셋을 삭제하시겠습니까?',
		deleteSuccess: '삭제되었습니다.',
		deleteError: '삭제 중 오류가 발생했습니다.',
	},
	shadcnDialog: {
		confirm: '확인',
		cancel: '취소',
	},
};
